### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by MacyChan** [UBC-MDS/web_and_cloud_group_1#1]
- By Thursday

Task
- [x] Team-work contract - @stevenleung2018 
- [x] Write introduction - @MacyChan  
- [x] Creating repository and project structure - @MacyChan 
- [x] Downloading the data - @MacyChan  
- [x] Combining data CSVs - @jo4356 
- [x] #2
- [x] #4

 Specific expectations for this milestone - @stevenleung2018 @stevenleung2018 @zackt113 @jo4356
