### ISSUE TITLE
Milestones 2

### ISSUE THREAD

**Issue by MacyChan** [UBC-MDS/web_and_cloud_group_1#11]
@MacyChan - By Mon 
@zackt113 - By Tue
@stevenleung2018 - By Thursday 4:00pm

Tasks

- [x] Setup your EC2 instance - @MacyChan 
- [x] Setup your JupyterHub - @MacyChan 
- [x] Setup the server - @MacyChan 
- [x] Get the data what we wrangled in our first milestone - Code Given
- [x] #12
- [x] Wrangle the data in preparation for machine learning - @zackt113 
- [x] How much time it took to read - @stevenleung2018 
- [x] Submission - @ jo4356

**Comment by stevenleung2018** [comment]
Now the "how much time to read" task is also done and covered by the PR (https://github.com/UBC-MDS/web_and_cloud_group_1/pull/13).
