### ISSUE TITLE
Milestones 3

### ISSUE THREAD

**Issue by MacyChan** [UBC-MDS/web_and_cloud_group_1#19]
Tasks

- [x] #20
- [x] Setup your browser, jupyter environment & connect to the master node - @stevenleung2018 (by Tue)
- [x] Develop a ML model using scikit-learn - @zackt113 (by Tue) 
- [x] Obtain best hyperparameter settings using spark's MLlib - @jo4356 (by Fri)
- [ ] Submission instructions - @MacyChan 

Next meeting at 11:00 am on Fri

**Comment by stevenleung2018** [comment]
@jo4356 When you do Task4, I need to start the EMR again.  So when you want to do that, you will need to let me know, and then I will need to start it and you will need to finish it within 4 hours.

Here are the steps:
1. I start the EMR for you and let you know when it is ready.  You will need to give me time as AWS needs time to spin up the instance.  (It's almost like redoing half of Task2 every time...  It takes time but it is not difficult.)
2. I will send the `pem` file to you separately.
3. Do Step 2.2 (https://github.ubc.ca/mds-2021-22/DSCI_525_web-cloud-comp_students/blob/master/release/milestone3/Milestone3.ipynb).  I will give you the command should look like `ssh -i ~/mds-525-001.pem -ND 8157 hadoop@ec2-18-236-217-159.us-west-2.compute.amazonaws.com` but the domain name of the EMR in the command may change.
4. Do Step 2.3.  You should only need to setup part once.  If it has already been set up, you would only need to enable to rule in FoxyProxy.
5. Do Step 2.4.  I will give you the URL of JupyterHub for you to put in FireFox.  The URL should look like `https://ec2-18-236-217-159.us-west-2.compute.amazonaws.com:9443/`.  It may change because the domain name may change.
6. Then you do what you need to do with Task4 on JupyterHub.  
7. You do NOT need to do Step 2.5.  I will do it for you unless you don't think the packages are properly installed and you want to reinstall them yourself.

Please remember to **download your notebook**.  Anything not downloaded will only be left in the EMR and it will be lost once terminated (every 4 hours...)

**Comment by stevenleung2018** [comment]
Actually I think Gittu will do more demonstrations at Lecture6 (April 13, 2022) on how to do SSH tunneling and also how to access services on EMR like JupyterHub.

**Comment by stevenleung2018** [comment]
By the way, in Milestone2, I accidentally created the S3 bucket on `us-east-1` region.  Now the EMR is on `us-west-2` region.  Just in case your code will have issue accessing the S3 bucket from the EMR, you can point to the one I have newly created on `us-west-2`.  The one on `us-east-1` has the URL beginning with `s3://mds-s3-001/`, right?  The one on `us-west-2` begins with `s3://mds-525-group1-us-west-2/`. I have cloned everything in this bucket to have the same files.
