### ISSUE TITLE
Milestone 4

### ISSUE THREAD

**Issue by stevenleung2018** [UBC-MDS/web_and_cloud_group_1#25]
- [x] Step 1: Develop the API. @MacyChan (by the end of Friday, April 22)
- [x] Step 2: Deploy the API (copy the app.py file to the EC2 instance.) @jo4356 (by the end of Monday, April 25)
- [x] Step 3: Summarize your journey.  @zackt113 (already done.  being reviewed by @stevenleung2018 and finish by the end of Friday, April 22.)
- [x] Step 4: Wrap up, check and submit. @stevenleung2018 (by 6pm, Thursday, April 28)

For reference, the Milestone4 instructions: 
https://github.ubc.ca/mds-2021-22/DSCI_525_web-cloud-comp_students/blob/master/release/milestone4/Milestone4.ipynb

Meeting before submission: 4pm, Tuesday, April 26.

**Comment by stevenleung2018** [comment]
@MacyChan @jo4356 @zackt113 Updated the issue per what we discussed just now.  Please let me know if there is anything wrong.

**Comment by stevenleung2018** [comment]
Submitted.  I also created a release for Milestone4.  Thanks for working together!
